// Copyright 2026 Adam Chalkley
//
// https://github.com/atc0005/check-memory
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/atc0005/check-memory/internal/config"
	"github.com/atc0005/check-memory/internal/memory"
	"github.com/atc0005/go-nagios"
	"github.com/rs/zerolog"
)

// 	// Fallback for older Linux kernels that might not have MemAvailable
// 	// In such cases, one might calculate using MemFree + Buffers + Cached,
// 	// though 'MemAvailable' is the modern, recommended metric.
// 	fmt.Println("MemAvailable field not found in /proc/meminfo. Consider older kernel calculations.")
// }

func main() {
	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Setup configuration by parsing user-provided flags.
	cfg, cfgErr := config.New(config.AppType{Plugin: true})
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case errors.Is(cfgErr, config.ErrHelpRequested):
		fmt.Println(cfg.Help())

		return

	case cfgErr != nil:

		// We make some assumptions when setting up our logger as we do not
		// have a working configuration based on sysadmin-specified choices.
		consoleWriter := zerolog.ConsoleWriter{Out: os.Stderr, NoColor: true}
		logger := zerolog.New(consoleWriter).With().Timestamp().Caller().Logger()

		logger.Err(cfgErr).Msg("Error initializing application")

		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	logger := cfg.Log.With().Logger()

	logger.Debug().
		Str("base_path", memory.ProcRootDir).
		Str("memstats_file", filepath.Join(memory.ProcRootDir, memory.ProcMemFilename)).
		Msg("Collecting memory info")

	memInfo, err := memory.GetMemInfo(cfg.CriticalThreshold, cfg.WarningThreshold)
	if err != nil {
		logger.Error().Err(err).Msg("Failed to evaluate memory usage")

		plugin.AddError(err)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to evaluate memory usage",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	logger.Debug().
		Int64("available_memory", memInfo.Available.Value).
		Int64("total_memory", memInfo.Available.Value).
		Msg("Memory Info successfully collected")

	pd := getPerfData(memInfo, cfg.CriticalThreshold, cfg.WarningThreshold)
	if err := plugin.AddPerfData(false, pd...); err != nil {
		logger.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)
	}

	serviceOutputTemplate := "%s: %s (%s%%) available memory"
	// longServiceOutputTemplate := "Total Memory: %s%sMemory Available: %s%s"

	switch {
	case !memInfo.IsOKState():
		logger.Debug().
			Int64("available_memory", memInfo.Available.Value).
			Int64("total_memory", memInfo.Available.Value).
			Msg("Available memory below specified threshold")

		plugin.AddError(memory.ErrAvailableMemoryBelowThreshold)

		plugin.ExitStatusCode = memInfo.ServiceState().ExitCode

		plugin.ServiceOutput = fmt.Sprintf(
			serviceOutputTemplate,
			memInfo.ServiceState().Label,
			memInfo.Available.String(),
			memInfo.PercentageAvailable().String(),
		)

		// plugin.LongServiceOutput = fmt.Sprintf(
		// 	longServiceOutputTemplate,
		// 	memInfo.Total.String(),
		// 	nagios.CheckOutputEOL,
		// 	memInfo.Available.String(),
		// 	nagios.CheckOutputEOL,
		// )

	default:

		logger.Debug().Msg("Available memory greater than specified thresholds.")

		plugin.ExitStatusCode = memInfo.ServiceState().ExitCode

		plugin.ServiceOutput = fmt.Sprintf(
			serviceOutputTemplate,
			memInfo.ServiceState().Label,
			memInfo.Available.String(),
			memInfo.PercentageAvailable().String(),
		)

		// plugin.LongServiceOutput = fmt.Sprintf(
		// 	longServiceOutputTemplate,
		// 	memInfo.Total.String(),
		// 	nagios.CheckOutputEOL,
		// 	memInfo.Available.String(),
		// 	nagios.CheckOutputEOL,
		// )

		return

	}
}
